[package]
name = "newsletter-rs"
version = "0.1.0"
authors = ["Luis Jesus Diaz Manzo <luis@drconopoima.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
repository = "https://github.com/drconopoima/newsletter-rs.git"

[lib]
path="src/lib.rs"

[[bin]]
path="src/main.rs"
name="newsletter-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version="^4.0.0-beta.21" }
serde = {version = "~1", features=["derive"]}
tokio = { version = "~1", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
actix = "~0.12"
actix-rt = "~2"
reqwest = "~0.11"
