application_port: 8000
application_address: "0.0.0.0"
admin_port: 65080
admin_address: "127.0.0.1"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database: "newsletter"
database_migration:
  migrate: false
  folder: "./migrations"
