application:
  address: "0.0.0.0"
database:
  ssl:
    tls: true
    cacertificates: |
      -----BEGIN CERTIFICATE-----
      M***EXAMPLE***
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      M***EXAMPLE***
      -----END CERTIFICATE-----
