application:
  address: 0.0.0.0
database:
  ssl:
    tls: true
    # Additional trusted certificate authorities
    # System's CAs trusted by default
    cacertificates: |
      -----BEGIN CERTIFICATE-----
      M***EXAMPLE***
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      M***EXAMPLE***
      -----END CERTIFICATE-----
